services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@db:5432/member_develop_logs_production
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
  bundle: 