services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
    depends_on:
      - db
    restart: always

  web-test:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails test
    volumes:
      - bundle:/usr/local/bundle
    environment:
      - RAILS_ENV=test
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
  bundle: 